/*
 * TechnoQuizBowlXView.java
 */

package technoquizbowlx;

import org.jdesktop.application.Action;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import org.jdesktop.application.TaskMonitor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.Icon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.*;
import javax.sound.midi.*;
import javax.sound.sampled.*;
import java.io.*;
/**
 * The application's main frame.
 */
public class TechnoQuizBowlXView extends FrameView {
    int qnum;//counter variable for questions
  
    int score; //variable for the score

    boolean clicked = false;




    public TechnoQuizBowlXView(SingleFrameApplication app) {
        super(app);

        initComponents();




        // status bar initialization - message timeout, idle icon and busy animation, etc
        ResourceMap resourceMap = getResourceMap();
        int messageTimeout = resourceMap.getInteger("StatusBar.messageTimeout");
        messageTimer = new Timer(messageTimeout, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                statusMessageLabel.setText("");
            }
        });
        messageTimer.setRepeats(false);
        int busyAnimationRate = resourceMap.getInteger("StatusBar.busyAnimationRate");
        for (int i = 0; i < busyIcons.length; i++) {
            busyIcons[i] = resourceMap.getIcon("StatusBar.busyIcons[" + i + "]");
        }
        busyIconTimer = new Timer(busyAnimationRate, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                busyIconIndex = (busyIconIndex + 1) % busyIcons.length;
                statusAnimationLabel.setIcon(busyIcons[busyIconIndex]);
            }
        });
        idleIcon = resourceMap.getIcon("StatusBar.idleIcon");
        statusAnimationLabel.setIcon(idleIcon);
        progressBar.setVisible(false);

        // connecting action tasks to status bar via TaskMonitor
        TaskMonitor taskMonitor = new TaskMonitor(getApplication().getContext());
        taskMonitor.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                String propertyName = evt.getPropertyName();
                if ("started".equals(propertyName)) {
                    if (!busyIconTimer.isRunning()) {
                        statusAnimationLabel.setIcon(busyIcons[0]);
                        busyIconIndex = 0;
                        busyIconTimer.start();
                    }
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(true);
                } else if ("done".equals(propertyName)) {
                    busyIconTimer.stop();
                    statusAnimationLabel.setIcon(idleIcon);
                    progressBar.setVisible(false);
                    progressBar.setValue(0);
                } else if ("message".equals(propertyName)) {
                    String text = (String)(evt.getNewValue());
                    statusMessageLabel.setText((text == null) ? "" : text);
                    messageTimer.restart();
                } else if ("progress".equals(propertyName)) {
                    int value = (Integer)(evt.getNewValue());
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(false);
                    progressBar.setValue(value);
                }
            }
        });
    }

    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = TechnoQuizBowlXApp.getApplication().getMainFrame();
            aboutBox = new TechnoQuizBowlXAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        TechnoQuizBowlXApp.getApplication().show(aboutBox);
    }




    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();
        statusPanel = new javax.swing.JPanel();
        javax.swing.JSeparator statusPanelSeparator = new javax.swing.JSeparator();
        statusMessageLabel = new javax.swing.JLabel();
        statusAnimationLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        buttonGroup1 = new javax.swing.ButtonGroup();

        mainPanel.setName("mainPanel"); // NOI18N

        buttonGroup1.add(jRadioButton1);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(technoquizbowlx.TechnoQuizBowlXApp.class).getContext().getResourceMap(TechnoQuizBowlXView.class);
        jRadioButton1.setText(resourceMap.getString("jRadioButton1.text")); // NOI18N
        jRadioButton1.setName("jRadioButton1"); // NOI18N

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText(resourceMap.getString("jRadioButton2.text")); // NOI18N
        jRadioButton2.setName("jRadioButton2"); // NOI18N

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText(resourceMap.getString("jRadioButton3.text")); // NOI18N
        jRadioButton3.setActionCommand(resourceMap.getString("jRadioButton3.actionCommand")); // NOI18N
        jRadioButton3.setName("jRadioButton3"); // NOI18N

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText(resourceMap.getString("jRadioButton4.text")); // NOI18N
        jRadioButton4.setActionCommand(resourceMap.getString("jRadioButton4.actionCommand")); // NOI18N
        jRadioButton4.setName("jRadioButton4"); // NOI18N

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setIcon(resourceMap.getIcon("jLabel2.icon")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton4)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton1))
                        .addContainerGap())
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                        .addGap(777, 777, 777))))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton1)
                .addContainerGap(817, Short.MAX_VALUE))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(479, Short.MAX_VALUE))
        );

        menuBar.setName("menuBar"); // NOI18N

        fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(technoquizbowlx.TechnoQuizBowlXApp.class).getContext().getActionMap(TechnoQuizBowlXView.class, this);
        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
        helpMenu.setName("helpMenu"); // NOI18N

        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        statusPanel.setName("statusPanel"); // NOI18N

        statusPanelSeparator.setName("statusPanelSeparator"); // NOI18N

        statusMessageLabel.setName("statusMessageLabel"); // NOI18N

        statusAnimationLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusAnimationLabel.setName("statusAnimationLabel"); // NOI18N

        progressBar.setName("progressBar"); // NOI18N

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusPanelSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 893, Short.MAX_VALUE)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusMessageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 723, Short.MAX_VALUE)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusAnimationLabel)
                .addContainerGap())
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addComponent(statusPanelSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusMessageLabel)
                    .addComponent(statusAnimationLabel)
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        setComponent(mainPanel);
        setMenuBar(menuBar);
        setStatusBar(statusPanel);
    }// </editor-fold>                        

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
        //ADD code here
     //  Start Question 1

      
        jButton1.setText("Next Question");
         clicked = true;

        if (qnum==0)
       {
  //
          try {
        // From file
     Sequence sequence = MidiSystem.getSequence(new File("23ywhnb.mid"));

        // Create a sequencer for the sequence
      Sequencer sequencer = MidiSystem.getSequencer();
     sequencer.open();
       sequencer.setSequence(sequence);

        // Start playing
     sequencer.start();

   } catch (IOException e) {
    } catch (MidiUnavailableException e) {
    } catch (InvalidMidiDataException e) {
   }

   score = 0;
   qnum = 1;
       }


         if (qnum==1)
         {

             

        jLabel1.setText(qnum + ") What term refers to the physical layout of a network's computers, cables and other resources?");
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/start1a.gif")));
      
        jRadioButton1.setText("a) Data Structure");
        jRadioButton2.setText("b) Topology");
        jRadioButton3.setText("c) Infrastructure");
        jRadioButton4.setText("d) Skeleton");
         }
         //  Question 1 Check
        
        if (qnum ==1 && clicked == true)
        {
       if (jRadioButton1.isSelected())
       {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B1.gif")));
           score = score - 5;
            ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
            qnum ++;

            clicked =false;
       }
        else if (jRadioButton2.isSelected())
         {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/gooda1.gif")));
           score = score + 5;


                 ///Start Audio Wav info for correct info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("gatling2.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////

        qnum ++;
            clicked =false;
        }
         else if (jRadioButton3.isSelected())
               {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B1.gif")));
           score = score - 5;
             ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
            clicked =false;
        }
         else if (jRadioButton4.isSelected())
           {
            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B1.gif")));
           score = score - 5;
             ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
            clicked =false;

             }
       jLabel3.setText("Score: " + score);
        }

         if (qnum == 2)
        {
        jLabel1.setText(qnum + ") True or False: With Cat-5 Cables, the more twists make it worse.");
    //    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/start1a.gif")));

        jRadioButton1.setText("a. True");
        jRadioButton2.setText("b. False");
        jRadioButton3.setText("");
        jRadioButton4.setText("");
               }
         if (qnum == 2 && clicked==true)
         {
         if (jRadioButton1.isSelected())
       {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B2.gif")));
           score = score - 5;
             ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
           qnum ++;
           clicked =false;
       }
        else if (jRadioButton2.isSelected())
         {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/gooda2.gif")));
           score = score + 5;
            ///Start Audio Wav info for correct info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("gatling2.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
            qnum ++;
            clicked =false;
             }
         else if (jRadioButton3.isSelected())
         {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B2.gif")));
           score = score - 5;
             ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
       qnum ++;
           clicked =false;
             }
         else if (jRadioButton4.isSelected())
            {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B2.gif")));
           score = score - 5;
             ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
       qnum ++;
           clicked =false;
             }
        jLabel3.setText("Score: " + score);

        }

        if (qnum == 3)
        {
          jLabel1.setText(qnum + ") A Linux program made for an x86 version of Linux will NOT run natively under a Windows operating system, because both Windows and Linux distributions are made to run on the Intel compatible CPUs and motherboards.");
   
        jRadioButton1.setText("True");
        jRadioButton2.setText("False");
        jRadioButton3.setText("");
        jRadioButton4.setText("");

        }

                  if (qnum == 3 && clicked==true)
         {
         if (jRadioButton1.isSelected())
       {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/gooda3.gif")));
           score = score + 5;
            ///Start Audio Wav info for correct info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("gatling2.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
           clicked =false;
       }
        else if (jRadioButton2.isSelected())
         {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B3.gif")));
           score = score - 5;
             ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
            clicked =false;
        }
         else if (jRadioButton3.isSelected())
            {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B3.gif")));
           score = score - 5;
             ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
            clicked =false;
             }
         else if (jRadioButton4.isSelected())
            {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B3.gif")));
           score = score - 5;
             ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
       qnum ++;
            clicked =false;
             }
        jLabel3.setText("Score: " + score);

        }

          if (qnum == 4)
        {
          jLabel1.setText(qnum + ") A Network Operating System can be installed through the network, without the use of a CD-ROM or floppy disk.");

        jRadioButton1.setText("a. True");
        jRadioButton2.setText("b. False");
        jRadioButton3.setText("");
        jRadioButton4.setText("");
        }

           if (qnum == 4 && clicked==true)
         {
         if (jRadioButton1.isSelected())
     {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/gooda4.gif")));
           score = score + 5;
            ///Start Audio Wav info for correct info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("gatling2.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
       qnum ++;
            clicked =false;
             }
        else if (jRadioButton2.isSelected())
         {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B4.gif")));
           score = score - 5;
             ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
            clicked =false;
             }


         else if (jRadioButton3.isSelected())
            {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B4.gif")));
           score = score - 5;
             ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
            clicked =false;
             }
         else if (jRadioButton4.isSelected())
         {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B4.gif")));
           score = score - 5;
             ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
            clicked =false;
             }
        jLabel3.setText("Score: " + score);

        }

          if (qnum == 5)
        {
          jLabel1.setText(qnum + ")True or False: Social Engineering does not require someone to have advanced technical knowledge.");

        jRadioButton1.setText("True");
        jRadioButton2.setText("False");
        jRadioButton3.setText("");
        jRadioButton4.setText("");
        }

           if (qnum == 5 && clicked==true)
         {
         if (jRadioButton1.isSelected())
     {
            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/gooda5.gif")));
           score = score + 5;
            ///Start Audio Wav info for correct info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("gatling2.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
            clicked =false;
       }
        else if (jRadioButton2.isSelected())
           {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B5.gif")));
           score = score - 5;
             ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
           clicked =false;

        }
         else if (jRadioButton3.isSelected())
              {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B5.gif")));
           score = score - 5;
             ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
           clicked =false;

        }
         else if (jRadioButton4.isSelected())
            {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B5.gif")));
           score = score - 5;
             ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
       qnum ++;
            clicked =false;
             }
        jLabel3.setText("Score: " + score);

        }

               if (qnum == 6)
        {
          jLabel1.setText(qnum + ") True or False:  Using a driver made for Windows XP will guarantee that your device will work properly under Windows Vista.");

        jRadioButton1.setText("True");
        jRadioButton2.setText("False");
        jRadioButton3.setText("");
        jRadioButton4.setText("");
        }

           if (qnum == 6 && clicked==true)
         {
         if (jRadioButton1.isSelected())
       {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B6.gif")));
           score = score - 5;
             ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
           clicked =false;
       }
        else if (jRadioButton2.isSelected())
           {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/gooda6.gif")));
           score = score + 5;
            ///Start Audio Wav info for correct info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("gatling2.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
            clicked =false;
        }
         else if (jRadioButton3.isSelected())
             {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B6.gif")));
           score = score - 5;
             ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
           clicked =false;
       }
         else if (jRadioButton4.isSelected())
              {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B6.gif")));
           score = score - 5;
             ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
            clicked =false;
             }
        jLabel3.setText("Score: " + score);

        }

                      if (qnum == 7)
        {
          jLabel1.setText(qnum + ") True or False:  Introducing handheld devices into a network environment increases the number of security liabilities and makes it necessary for new policies to be put in place.");

        jRadioButton1.setText("True");
        jRadioButton2.setText("False");
        jRadioButton3.setText("");
        jRadioButton4.setText("");
        }

           if (qnum == 7 && clicked==true)
         {
         if (jRadioButton1.isSelected())
           {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/gooda7.gif")));
           score = score + 5;
            ///Start Audio Wav info for correct info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("gatling2.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
           clicked =false;
        }
        else if (jRadioButton2.isSelected())
         {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B7.gif")));
           score = score - 5;
             ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
            clicked =false;
        }
         else if (jRadioButton3.isSelected())
        {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B7.gif")));
           score = score - 5;
             ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
            clicked =false;

       }
         else if (jRadioButton4.isSelected())
            {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B7.gif")));
           score = score - 5;
             ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
       qnum ++;
            clicked =false;
             }
        jLabel3.setText("Score: " + score);

        }

            if (qnum == 8)
        {
          jLabel1.setText(qnum + " )True or False:  A brand new computer that you buy today has a high chance of supporting ISA cards.");

        jRadioButton1.setText("True");
        jRadioButton2.setText("False");
        jRadioButton3.setText("");
        jRadioButton4.setText("");
        }

           if (qnum == 8 && clicked==true)
         {
         if (jRadioButton1.isSelected())
       {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B8.gif")));
           score = score - 5;
             ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
           clicked =false;
       }
        else if (jRadioButton2.isSelected())
         {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/gooda8.gif")));
           score = score + 5;
            ///Start Audio Wav info for correct info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("gatling2.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
            clicked =false;
        }
         else if (jRadioButton3.isSelected())
            {
            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B8.gif")));
           score = score - 5;
             ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
           clicked =false;
             }
         else if (jRadioButton4.isSelected())
            {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B8.gif")));
           score = score - 5;
             ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
       qnum ++;
            clicked =false;
             }
        jLabel3.setText("Score: " + score);

        }

           if (qnum == 9)
        {
          jLabel1.setText(qnum + ") True or False: VPNs should include web services and should not be placed in demilitarized zones");

        jRadioButton1.setText("a. True");
        jRadioButton2.setText("b. False");
        jRadioButton3.setText("");
        jRadioButton4.setText("");
        }

           if (qnum == 9 && clicked==true)
         {
         if (jRadioButton1.isSelected())
       {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B9.gif")));
           score = score - 5;
             ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
           clicked =false;
       }
        else if (jRadioButton2.isSelected())
        {
             jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/gooda9.gif")));
           score = score + 5;
            ///Start Audio Wav info for correct info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("gatling2.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
       qnum ++;
            clicked =false;
             }
         else if (jRadioButton3.isSelected())
            {
            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B9.gif")));
           score = score - 5;
             ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
           clicked =false;
             }
         else if (jRadioButton4.isSelected())
            {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B9.gif")));
           score = score - 5;
             ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
            clicked =false;
             }
        jLabel3.setText("Score: " + score);

        }

          if (qnum == 10)
        {
          jLabel1.setText(qnum + ")You can always use the same policy and procedures for all environments, because they are all fundamentally the same?");

        jRadioButton1.setText("True");
        jRadioButton2.setText("False");
        jRadioButton3.setText("");
        jRadioButton4.setText("");
        }

           if (qnum == 10 && clicked==true)
         {
         if (jRadioButton1.isSelected())
       {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B10.gif")));
           score = score - 5;
             ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
            clicked =false;

       }
        else if (jRadioButton2.isSelected())
         {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/gooda10.gif")));
           score = score + 5;
            ///Start Audio Wav info for correct info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("gatling2.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
           clicked =false;
        }
         else if (jRadioButton3.isSelected())
            {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B10.gif")));
           score = score - 5;
             ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
            clicked =false;
             }
         else if (jRadioButton4.isSelected())
            {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B10.gif")));
           score = score - 5;
             ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
       qnum ++;
            clicked =false;
             }
        jLabel3.setText("Score: " + score);

        }

          if (qnum == 11)
        {
          jLabel1.setText(qnum + ") If a paper document of a file is left on a table it is not a breach of security, because the digital version of the document is encrypted and locked on the original workstation.");

        jRadioButton1.setText("True");
        jRadioButton2.setText("False");
        jRadioButton3.setText("");
        jRadioButton4.setText("");
        }

           if (qnum == 11 && clicked==true)
         {
         if (jRadioButton1.isSelected())
       {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B11.gif")));
           score = score - 5;
             ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
           clicked =false;
       }
        else if (jRadioButton2.isSelected())
         {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/gooda11.gif")));
           score = score + 5;
            ///Start Audio Wav info for correct info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("gatling2.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
            clicked =false;
        }
         else if (jRadioButton3.isSelected())
              {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B11.gif")));
           score = score - 5;
             ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
            clicked =false;
        }
         else if (jRadioButton4.isSelected())
          {
            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B11.gif")));
           score = score - 5;
             ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
            clicked =false;
             }
        jLabel3.setText("Score: " + score);

        }

          if (qnum == 12)
        {
          jLabel1.setText(qnum + ") Reconstructing information and capability using RAID and UPS is known as:");

        jRadioButton1.setText("a. Fail Over");
        jRadioButton2.setText("b. Backup");
        jRadioButton3.setText("c. Balance");
        jRadioButton4.setText("d. Lap Over");
        }

           if (qnum == 12 && clicked==true)
         {
         if (jRadioButton1.isSelected())
       {
            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/gooda12.gif")));
           score = score + 5;
            ///Start Audio Wav info for correct info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("gatling2.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
            clicked =false;
       }
        else if (jRadioButton2.isSelected())
               {
            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B12.gif")));
           score = score - 5;
             ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
           clicked =false;
       }
         else if (jRadioButton3.isSelected())
           {
            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B12.gif")));
           score = score - 5;
             ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
           clicked =false;

        }
         else if (jRadioButton4.isSelected())
            {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B12.gif")));
           score = score - 5;
             ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
       qnum ++;
            clicked =false;
             }
        jLabel3.setText("Score: " + score);

        }

         if (qnum == 13)
        {
          jLabel1.setText(qnum + ") True or False: Since Information Security primarily deals with computers and networks, there is no need to worry about physical security or natural disasters?");

        jRadioButton1.setText("True");
        jRadioButton2.setText("False");
        jRadioButton3.setText("");
        jRadioButton4.setText("");
        }

           if (qnum == 13 && clicked==true)
         {
         if (jRadioButton1.isSelected())
       {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B13.gif")));
           score = score - 5;
             ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
           clicked =false;
       }
        else if (jRadioButton2.isSelected())
         {
            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/gooda13.gif")));
           score = score + 5;
            ///Start Audio Wav info for correct info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("gatling2.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
            clicked =false;
       }
         else if (jRadioButton3.isSelected())
             {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B13.gif")));
           score = score - 5;
             ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
           clicked =false;
        }
         else if (jRadioButton4.isSelected())
            {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B13.gif")));
           score = score - 5;
             ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
       qnum ++;
            clicked =false;
             }
        jLabel3.setText("Score: " + score);

        }

           if (qnum == 14)
        {
          jLabel1.setText(qnum + ") What is the command to see your Network Settings in Windows?");

        jRadioButton1.setText("a. ifconfig");
        jRadioButton2.setText("b. NTConfig");
        jRadioButton3.setText("c. netstart");
        jRadioButton4.setText("d. ipconfig");
        }

           if (qnum == 14 && clicked==true)
         {
         if (jRadioButton1.isSelected())
     {
            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B14.gif")));
           score = score - 5;
             ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
            clicked =false;
             }
        else if (jRadioButton2.isSelected())
         {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B14.gif")));
           score = score - 5;
             ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
            clicked =false;
        }
         else if (jRadioButton3.isSelected())
            {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B14.gif")));
           score = score - 5;
             ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
            clicked =false;
        }
         else if (jRadioButton4.isSelected())
            {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/gooda14.gif")));
           score = score + 5;
            ///Start Audio Wav info for correct info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("gatling2.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
            clicked =false;
             }
        jLabel3.setText("Score: " + score);

        }

                    if (qnum == 15)
        {
          jLabel1.setText(qnum + ") True or False:  Computer crimes are not treated the same across all states.");

        jRadioButton1.setText("a. True");
        jRadioButton2.setText("b. False");
        jRadioButton3.setText("");
        jRadioButton4.setText("");
        }

           if (qnum == 15 && clicked==true)
         {
         if (jRadioButton1.isSelected())
      {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/gooda15.gif")));
           score = score + 5;
            ///Start Audio Wav info for correct info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("gatling2.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
       qnum ++;
            clicked =false;
             }
        else if (jRadioButton2.isSelected())
         {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B15.gif")));
           score = score - 5;
             ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
            clicked =false;
        }
         else if (jRadioButton3.isSelected())
            {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B15.gif")));
           score = score - 5;
             ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
            clicked =false;
             }
         else if (jRadioButton4.isSelected())
            {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B15.gif")));
           score = score - 5;
             ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
            clicked =false;
        }
        jLabel3.setText("Score: " + score);

        }


         ///Code added l  11/5/2010*///

                    if (qnum == 16)
        {
          jLabel1.setText(qnum + ") Authentication does not involve:");

        jRadioButton1.setText("a. Something you have");
        jRadioButton2.setText("b. Something you are");
        jRadioButton3.setText("c. Something you feel");
        jRadioButton4.setText("d. Something you know");
        }

           if (qnum == 16 && clicked==true)
         {
         if (jRadioButton1.isSelected())
       {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B6.gif")));
           score = score - 5;
             ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
           clicked =false;
       }
        else if (jRadioButton2.isSelected())
         {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B6.gif")));
           score = score - 5;
             ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
            clicked =false;
        }
         else if (jRadioButton3.isSelected())
              {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/gooda6.gif")));
           score = score + 5;
            ///Start Audio Wav info for correct info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("gatling2.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
            clicked =false;
        }
         else if (jRadioButton4.isSelected())
              {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B6.gif")));
           score = score - 5;
             ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
            clicked =false;
             }
        jLabel3.setText("Score: " + score);

        }

                      if (qnum == 17)
        {
          jLabel1.setText(qnum + ")True or False:  Trust is not Universal, but dishonesty is.");

        jRadioButton1.setText("a. True");
        jRadioButton2.setText("b. False");
        jRadioButton3.setText("");
        jRadioButton4.setText("");
        }

           if (qnum == 17 && clicked==true)
         {
         if (jRadioButton1.isSelected())
           {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/gooda7.gif")));
           score = score + 5;
            ///Start Audio Wav info for correct info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("gatling2.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
           clicked =false;
        }
        else if (jRadioButton2.isSelected())
         {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B7.gif")));
           score = score - 5;
             ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
            clicked =false;
        }
         else if (jRadioButton3.isSelected())
        {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B7.gif")));
           score = score - 5;
             ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
            clicked =false;

       }
         else if (jRadioButton4.isSelected())
            {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B7.gif")));
           score = score - 5;
             ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
       qnum ++;
            clicked =false;
             }
        jLabel3.setText("Score: " + score);

        }


          if (qnum == 18)
        {
          jLabel1.setText(qnum + ") You see someone enter into your facility wearing a FedEx uniform carrying what appears to be a package.  The person then asks you to enter a secured room.  What do you do?");

        jRadioButton1.setText("a. Require the person to show proof of who they are and check that the package is legit");
        jRadioButton2.setText("b. Let them in with the package");
        jRadioButton3.setText("c. Kick the person out immediately and just take the package");
        jRadioButton4.setText("d. Detain the carrier and hose down the package");
        }

           if (qnum == 18 && clicked==true)
         {
         if (jRadioButton1.isSelected())
      {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/gooda15.gif")));
           score = score + 5;
            ///Start Audio Wav info for correct info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("gatling2.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
       qnum ++;
            clicked =false;
             }
        else if (jRadioButton2.isSelected())
         {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B15.gif")));
           score = score - 5;
             ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
            clicked =false;
        }
         else if (jRadioButton3.isSelected())
            {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B15.gif")));
           score = score - 5;
             ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
            clicked =false;
             }
         else if (jRadioButton4.isSelected())
            {
           jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/technoquizbowlx/resources/Level1B15.gif")));
           score = score - 5;
             ///Start Audio Wav info for wrong info/////
    try {
         AudioInputStream stream =
                  AudioSystem.getAudioInputStream(
                    new File("laser.wav"));

 	AudioFormat format = stream.getFormat();
        DataLine.Info info =
                  new DataLine.Info(Clip.class,
                          stream.getFormat());
        Clip clip = (Clip) AudioSystem.getLine(info);

        clip.open(stream);
        clip.start();

      } catch (Exception e) {
           e.printStackTrace();
      }
///End Audio Wav info/////
        qnum ++;
            clicked =false;
        }
        jLabel3.setText("Score: " + score);

        }


         if(qnum > 18)
         {
              jLabel1.setText("Game Over");

        jRadioButton1.setText("Game Over");
        jRadioButton2.setText("Game Over");
        jRadioButton3.setText("Game Over");
        jRadioButton4.setText("Game Over");

         }

    }                                     

    // Variables declaration - do not modify                     
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel statusAnimationLabel;
    private javax.swing.JLabel statusMessageLabel;
    private javax.swing.JPanel statusPanel;
    // End of variables declaration                   



    private final Timer messageTimer;
    private final Timer busyIconTimer;
    private final Icon idleIcon;
    private final Icon[] busyIcons = new Icon[15];
    private int busyIconIndex = 0;

    private JDialog aboutBox;




}
